# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model simpleFC
.dummy t0 t1 t2 t4 t5 t6 t3 t7
.graph
t0 p0 p1
t1 p2
t2 p3
t4 p3
t5 p6
t6 p7
t3 p4 p5 p8
t7 p9
p0 t1 t2
p1 t3
p2 t4
p3 t0
p4 t5
p5 t6
p6 t0
p7 t0
p8 t7
p9 t0
.marking {p0 p1}
.end
