# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model xorGATE
.dummy a_M a_P b_M b_P
.outputs out_M out_P
.internal t0 t5 t6 t8 t7
.graph
b_M p5
t0 p0 p1
a_M p3
b_P p4
out_P p8
t5 p6
t6 p6
t8 p7
a_P p2
out_M p8
t7 p7
p7 out_M
p4 t5 t7
p3 t7 t8
p1 b_M b_P
p0 a_M a_P
p6 out_P
p5 t6 t8
p8 t0
p2 t5 t6
.marking {p0 p1}
.end
