# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.4
.model half
.inputs Ri_MINUS Ri_PLUS Ai_MINUS Ai_PLUS
.outputs Ao_MINUS Ao_PLUS Ro_MINUS Ro_PLUS
.graph
Ao_PLUS p0 p10
Ri_MINUS p1
Ao_MINUS p2
Ri_PLUS p7
Ro_PLUS p3 p8
Ai_PLUS p4
Ro_MINUS p5 p9
Ai_MINUS p6
p0 Ri_MINUS
p1 Ao_MINUS
p2 Ri_PLUS
p3 Ai_PLUS
p4 Ro_MINUS
p5 Ai_MINUS
p6 Ro_PLUS
p7 Ro_PLUS
p8 Ao_PLUS
p9 Ao_MINUS
p10 Ro_MINUS
.marking {p6 p7}
.end
