# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.dummy t0 t1 t2 t3 t4 t5 t6
.graph
t0 p2 p3
t1 p4 p5
t2 p6
t3 p7
t4 p6
t5 p7
t6 p0 p1
p0 t0 t1
p1 t0 t1
p2 t2
p3 t3
p4 t4
p5 t5
p6 t6
p7 t6
.marking {p0 p1}
.end
