# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model toggle
.inputs Ri_MINUS Ri_PLUS
.outputs Ro1_MINUS Ro1_PLUS Ro2_MINUS Ro2_PLUS
.graph
Ri_PLUS p0 p2
Ri_MINUS p1 p3
Ro1_PLUS p4 p5
Ro1_MINUS p4 p9
Ro2_PLUS p6 p7
Ro2_MINUS p7 p8
p0 Ri_MINUS
p1 Ri_PLUS
p2 Ro1_MINUS Ro1_PLUS
p3 Ro2_MINUS Ro2_PLUS
p4 Ri_MINUS
p5 Ro1_MINUS
p6 Ro2_MINUS
p7 Ri_PLUS
p8 Ro2_PLUS
p9 Ro1_PLUS
.marking {p1 p7 p8 p9}
.end
