# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.3
.model andGATE
.inputs a_P a_M b_P b_M
.outputs out_P out_M
.internal t5 t6 t7 t8
.graph
a_P p2
a_M p3
b_P p4
b_M p5
t5 p6
t6 p6
t7 p6
t8 p7
out_P p0 p1
out_M p0 p1
p0 a_M a_P
p1 b_M b_P
p2 t5 t6
p3 t7 t8
p4 t5 t7
p5 t6 t8
p6 out_P
p7 out_M
.marking {p0 p1}
.end
