# STG file generated by Workcraft 3 (Return of the Hazard), version 3.2.0
.model Untitled
.inputs t0 t1 t2 t5 t6 t3 t7
.outputs t4
.graph
t0 p0 p1
t1 p2
t2 p3
t4 p3
t5 p6
t6 p6
t3 p4
t7 p5
p0 t1 t2
p1 t3 t7
p2 t4
p3 t0
p4 t5
p5 t6
p6 t0
.marking {p0 p1}
.end
